[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sigmaker"
requires-python = ">= 3.10"
version = "1.3.0"
authors = [{ name = "Mahmoud Abdelkader" }]
description = "IDA Pro plugin to generate signatures for code"
dependencies = []

[project.optional-dependencies]
ci = ["coverage"]
